.TH siteuptime 1 "November 2004" "siteuptime (wzdftpd)" "wzdftpd tools"
.\" Process with
.\" groff -man -Tascii siteuptime.1 
.\"
.SH NAME
siteuptime \- show current uptime for FTP server (wzdftpd)
.SH SYNOPSIS
.B siteuptime [OPTION]
.SH DESCRIPTION
The
.BI siteuptime
command shows current uptime for wzdftpd.
.SH OPTIONS
.TP 12
.BI \-\-user,\-u " XXX"
Use username \fIXXX\fP instead of wzdftpd. 
.TP
.BI \-\-pass,\-w " XXX"
Use password \fIXXX\fP with the username.
.TP
.BI \-\-host,\-h " XXX"
Connect to the specified host.
.TP
.BI \-\-port,\-p " XXX"
Employ the specified port number for connecting to the server.
.TP
.BI \-\-secure,\-s
Enforce a secure connection, aborts if negotiation fails.
.TP
.BI \-\-insecure,\-t
Do not try to negotiate a secure connection.
.TP
.PD
.BR
.SH AUTHORS
.PP
wzdftpd is written and maintained by Pierre Chifflier <chifflier@cpe.fr>,
and some others contributors, full credits can be found in
.BR /usr/share/doc/wzdftpd/AUTHORS
.PD
.SH SEE ALSO
.BR wzdftpd(8), ftp(1), siteconfig(1), sitewho(1)
.PP
Full documentation on wzdftpd, including configuration and FAQs, is available at
.BR http://www.wzdftpd.net
.PP 
For help/support, try the wzdftpd mailing lists, detailed on
.BR http://sourceforge.net/mail/?group_id=78247
.PP
Report bugs at
.BR http://www.wzdftpd.net/smf/index.php
