
#define WZD_VERSION "${WZD_VERSION}"
#define WZD_VERSION_LONG "${WZD_VERSION_LONG}"

#define WZD_BUILD_NUM "${WZD_BUILD_NUM}"
#define WZD_BUILD_OPTS "${WZD_BUILD_OPTS}"

#define WZD_DEFAULT_CONF "${WZD_DEFAULT_CONF}"

