Document: wzdftpd
Title: Debian wzdftpd Manual
Author: <insert document author here>
Abstract: This manual describes what wzdftpd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wzdftpd/wzdftpd.sgml.gz

Format: postscript
Files: /usr/share/doc/wzdftpd/wzdftpd.ps.gz

Format: text
Files: /usr/share/doc/wzdftpd/wzdftpd.text.gz

Format: HTML
Index: /usr/share/doc/wzdftpd/html/index.html
Files: /usr/share/doc/wzdftpd/html/*.html

  
