# Comment this if you don't want SSL
SSL_SUPPORT=1

# Uncomment if you prefer sfv checker compiled in the exe
# + reduces the number of files
# - cannot be reloaded dynamically
#
# NOTE : as an evidence, it would be _stupid_ to enable internal sfv and
#   sfv module at the same time, so check your .cfg ...
#INTERNAL_SFV=1
