# Do not change this !
DATE_TAG:=$(shell date +"%Y%m%d")
PLATFORM := $(shell uname)

# RELEASE VERSION
WZD_VERSION_NUM=0.1rc3

# Installation Directory
DESTDIR=/tmp/wzdFTPd-$(WZD_VERSION_NUM)

# Comment this if you don't want SSL
SSL_SUPPORT=1

# Comment this if you want a mono-process thread (?)
WZD_MULTIPROCESS=1

# Uncomment if you prefer sfv checker compiled in the exe
# + reduces the number of files
# - cannot be reloaded dynamically
#
# NOTE : as an evidence, it would be _stupid_ to enable internal sfv and
#   sfv module at the same time, so check your .cfg ...
#INTERNAL_SFV=1
