IF (NOT BACKENDS_INSTALL_PATH)
  SET(BACKENDS_INSTALL_PATH "lib/wzdftpd/backends")
ENDIF (NOT BACKENDS_INSTALL_PATH)

IF (NOT MODULES_INSTALL_PATH)
  SET(MODULES_INSTALL_PATH "lib/wzdftpd/modules")
ENDIF (NOT MODULES_INSTALL_PATH)

IF (NOT CONF_INSTALL_PATH)
  SET(CONF_INSTALL_PATH "etc/wzdftpd")
ENDIF (NOT CONF_INSTALL_PATH)

IF (NOT HEADERS_INSTALL_PATH)
  SET(HEADERS_INSTALL_PATH "include")
ENDIF (NOT HEADERS_INSTALL_PATH)

IF (NOT DOC_INSTALL_PATH)
  SET(DOC_INSTALL_PATH "share/doc/wzdftpd")
ENDIF (NOT DOC_INSTALL_PATH)

IF (NOT MAN_INSTALL_PATH)
  SET(MAN_INSTALL_PATH "share/man")
ENDIF (NOT MAN_INSTALL_PATH)

# set variables for replacement in wzd.cfg.sample
SET(PACKAGE "wzdftpd")
SET(localstatedir "var")
SET(datadir "lib")
SET(sysconfdir "${CONF_INSTALL_PATH}")

IF(WIN32)
  SET(WZD_DEFAULT_CONF "wzd-win32.cfg")
ELSE(WIN32)
  SET(WZD_DEFAULT_CONF "${CONF_INSTALL_PATH}/wzd.cfg")
ENDIF(WIN32)

